### ISSUE TITLE
go1.19 support

### ISSUE THREAD

**Issue by mikeS7** [dmachard/go-dns-collector#112]
Got an error at runtime on latest main branch.

`panic: Something in this program imports go4.org/unsafe/assume-no-moving-gc to declare that it assumes a non-moving garbage collector, but your version of go4.org/unsafe/assume-no-moving-gc hasn't been updated to assert that it's safe against the go1.19 runtime. If you want to risk it, run with environment variable ASSUME_NO_MOVING_GC_UNSAFE_RISK_IT_WITH=go1.19 set. Notably, if go1.19 adds a moving garbage collector, this program is unsafe to use.`

**Comment by dmachard** [comment]
pull request #115 fixed this issue
