### ISSUE TITLE
Target is no longer accessible from Prometheus with the "expected label name, got "INVALID" error

### ISSUE THREAD

**Issue by ryhoofr** [dmachard/go-dns-collector#138]
The Prometheus polling falls off in case of a badly formed metric.
The error 'expected label name, got "INVALID' appears in the target section of Prometheus.

**Comment by dmachard** [comment]
This issue does not exist with the prometheus logger, prefer to use this one instead of the webserver logger.
Metrics will be removed in the future on the webserver api.

**Comment by dmachard** [comment]
New release v0.25.0 available with new dashboard and Prometheus logger!
