### ISSUE TITLE
Feature request: sink dnstap to a file instead of socket?

### ISSUE THREAD

**Issue by danielloader** [dmachard/go-dns-collector#176]
Thanks again for the pcap reading capacity, it's worked well!

Just wondered if it'd be possible if it's possible we could dump dnstap protobuf to a file, akin to the option bind offers?

https://kb.isc.org/docs/aa-01342

> A required dnstap-output option that specifies what to do with the captured packets. It is more efficient to send the captured packets to a process waiting to receive them than to write them to a file, but there is a configuration option that will write to a file.

We're looking to archive some dnstap data on S3 datalake for a slightly more compact, dns specific fileformat - being easier to parse in bulk in spark and other tools.

**Comment by danielloader** [comment]
Not sure if it'd make more sense for line-delimited base64 encoded protobuf in a file, or just back to back protobuf data into the file. 

I found the tool bind9 offers to read the files, might be useful for validating the output is working as expected. 

https://github.com/isc-projects/bind9/blob/main/bin/tools/dnstap-read.c

**Comment by danielloader** [comment]
https://developers.google.com/protocol-buffers/docs/techniques#streaming

Bit of digging later, might need to look at how bind does it in more detail because of the lack of self delimiting in the data stream.

**Comment by dmachard** [comment]
I will take a look, it should not be difficult to implement.

**Comment by danielloader** [comment]
Raising a question that could be a bug. 

The file watching action seems to be unhappy when you put large files into the watched directory, doesn't seem to wait until the file is completely copied and then reloads the file as the transfer is taking place.

I can't tell if it's just restarting the file reading process each time more data is flushed to the file but it ends up showing a loop of timestamp a when sinking to the console for debugging (same 15 seconds or so over and over again even though the segment is a 10 minute pcap).

I've just gone on annual leave so I'll have to dig up reproduction steps when I'm back in a week or so but thought it's worth raising now while you're working on it.

But I imagine you might be able to reproduce this with a pcap file with a couple tens of millions of dns requests in it that's a few GB in size.

It might be possible this is a difference in behaviour between a mv and a cp, due to the difference in action between moving a pointer on the filesystem and duplicating the data of a large file into the watched directory, and I was using copy to debug by reusing the same data repeatedly into the directory.

**Comment by dmachard** [comment]
Interesting, can you open a new issue for that ?
I will try to reproduce in my side, when I have more time.

**Comment by danielloader** [comment]
Closing the issue as I've had time to test it and the round trip conversion to .fstrm and back again seems to work. As you say it'll probably need some robust round trip tests to confirm but to the eye it looks fine!

Thanks
