### ISSUE TITLE
Potential issue with file watching of large pcap files

### ISSUE THREAD

**Issue by danielloader** [dmachard/go-dns-collector#187]
https://github.com/dmachard/go-dns-collector/issues/176#issuecomment-1331136003

Placeholder for this issue, will add more detail next week.

**Comment by dmachard** [comment]
I am using the following library to watch a folder: https://github.com/fsnotify/fsnotify
maybe it can help

**Comment by dmachard** [comment]
I succeed to reproduce in my side. I pushed a fix.

I fixed two things:
- move a file in the watching directory is now properly detected
- with cp, the collector now wait some seconds when no writing is detected before to read the file.

Thank to have report this issue, let me know when you test this fix.

**Comment by dmachard** [comment]
Fix is embedded in the[ v0.26.0-beta3](https://github.com/dmachard/go-dns-collector/releases/tag/v0.26.0-beta3) release!

**Comment by danielloader** [comment]
Thanks for working on this, can confirm it's handling it as expected.
