### ISSUE TITLE
Feature request: GZIP PCAP source file support

### ISSUE THREAD

**Issue by danielloader** [dmachard/go-dns-collector#196]
I might be misreading the dependant library code, but it seems to imply it can handle gzip source files:

https://github.com/google/gopacket/blob/3aa782ce48d4a525acaebab344cedabfb561f870/pcapgo/read.go#L30

If so, would it be possible to support `.pcap.gz` files too?

Thanks

**Comment by dmachard** [comment]
New v0.28.0-beta1 release available.
It should be supported with this version.
