### ISSUE TITLE
Availability Metric - count the number timeout queries

### ISSUE THREAD

**Issue by dmachard** [dmachard/go-dns-collector#210]
### Discussed in https://github.com/dmachard/go-dns-collector/discussions/189

<div type='discussions-op-text'>

<sup>Originally posted by **flz** December  5, 2022</sup>
I've been trying to wrap my head around how to create an availability metric based on what's already available.

The first thing that came to mind was to do something like that:

```
sum(rate(dnscollector_packets_total{op_name="CLIENT_RESPONSE"}[$__rate_interval])) / sum(rate(dnscollector_packets_total{op_name="CLIENT_QUERY"}[$__rate_interval]))
```

The issue with the above is that, because of the delay between query and response, you end up with a percentage higher than 100% (see below).

<img width="810" alt="Screen Shot 2022-12-04 at 8 55 14 PM" src="https://user-images.githubusercontent.com/48219/205552560-74da80d7-d396-4794-be2a-56b717fdd53c.png">

What I've been thinking of doing instead is changing the way the cache is working by adding a counter for entries evicted by the `query-timeout` and change the Get function to be more of a "pop" (get+delete). What the counter would indicate is the number queries for which no response was seen within `query-timeout seconds. 

My problem is then passing the counter to the loggers. I could add a new field/struct in DnsMessage and periodically pull the number from the cache but it seems a bit of a hack since that counter wouldn't related to the DnsMessage it would be a part of.

Thoughts?</div>

**Comment by dmachard** [comment]
@flz implement in next release with new metrics

**Comment by flz** [comment]
Looking forward to trying it out! Thanks @dmachard!

**Comment by dmachard** [comment]
More details about the config, you need to add the `latency` transform with the `unanswered-queries`  key to true

```
multiplexer:
  collectors:
    - name: tap
      dnstap:
        listen-ip: 0.0.0.0
        listen-port: 6000
      transforms:
        latency:
          unanswered-queries: true
          queries-timeout: 2
```

Associated metrics:

```
# HELP dnscollector_top_unanswered Number of hit per unanswered domain - topN
# TYPE dnscollector_top_unanswered gauge
dnscollector_top_unanswered{domain="test",stream_id="dns-collector"} 3
# HELP dnscollector_unanswered_total The total number of unanswered domains per stream identity
# TYPE dnscollector_unanswered_total counter
dnscollector_unanswered_total{stream_id="dns-collector"} 1
# HELP dnscollector_unanswered_uniq_total The total number of uniq unanswered domain
# TYPE dnscollector_unanswered_uniq_total counter
dnscollector_unanswered_uniq_total 1
```
