### ISSUE TITLE
Feature - Basic auth for prometheus logger

### ISSUE THREAD

**Issue by secure-xxx** [dmachard/go-dns-collector#236]
Hello, thank you very match for your work. Can you please add functionaity - basic auth for prometheus logger, similarry restapi logger?

**Comment by secure-xxx** [comment]
i'm sorry for my persistence, it's possible to implement?

**Comment by secure-xxx** [comment]
Thanks

**Comment by dmachard** [comment]
beta release available, any feedback will be appreciated

**Comment by secure-xxx** [comment]
Thanks a lot!!! Metrics run.

**Comment by flz** [comment]
@dmachard Can we make this optional? This is breaking on my end since my end since scraping expects an endpoint without authentication. I tried setting login/pwd to "" but that didn't work. Maybe a new basic-auth-enable boolean would help here?

**Comment by dmachard** [comment]
Yes I can with a new setting `basic-auth-enable`
But basic auth will still be enabled by default.

**Comment by dmachard** [comment]
Beta5 available with basic-auth-enable setting

**Comment by flz** [comment]
Works a charm! Thanks for the ultra-quick turnaround! 🙏🏻

**Comment by dmachard** [comment]
Implemented in release v0.30.0.

**Comment by secure-xxx** [comment]
all works fine in our production, large uptime
