### ISSUE TITLE
Soft reload configuration

### ISSUE THREAD

**Issue by KVInventoR** [dmachard/go-dns-collector#34]
I am not sure, have been it implemented or haven't, but it will be useful to have some soft reload configuration if configuration file was changed.

If configuration file was changed, just do automatic restart dns-collector process to apply new changes, this feature can be enabled over some configuration option.

**Comment by dmachard** [comment]
manual reload of the configuration on changed or automatic changed detection without restart of the dns-collector ?

**Comment by KVInventoR** [comment]
I will be good to have an option, where you can define both of this options

**Comment by dmachard** [comment]
New beta release 0.16.0-b2 available with SIGUP signal support to reload configuration

**Comment by dmachard** [comment]
Version 0.16.0  released since one week
Feel free to open a new issue.
