### ISSUE TITLE
Partition Loki streams by peer's identity

### ISSUE THREAD

**Issue by juliusrickert** [dmachard/go-dns-collector#37]
I think that partitioning the streams by the peer's—or DNS server's—identity would likely benefit many users.
This feature would speed up drilling down by DNS server without Loki needing to process the other server's logs.

**Comment by dmachard** [comment]
Supported in the new beta release [0.17.0-b3](https://github.com/dmachard/go-dns-collector/releases/tag/v0.17.0-b3)

**Comment by dmachard** [comment]
v0.17.0 released
