### ISSUE TITLE
Fault on initial install on MacOS Big Sur (others?)

### ISSUE THREAD

**Issue by johnhtodd** [dmachard/go-dns-collector#41]
Attempting to install from scratch on new system after a fresh "git clone":

zot12-2:dns-collector jtodd$ go run .
# github.com/dmachard/go-dnscollector/collectors
collectors/dnssniffer.go:86:11: undefined: unix.SockFprog
collectors/dnssniffer.go:91:9: undefined: unix.SetsockoptSockFprog
collectors/dnssniffer.go:91:58: undefined: syscall.SO_ATTACH_FILTER
collectors/dnssniffer.go:95:55: undefined: syscall.SO_DETACH_FILTER
collectors/dnssniffer.go:167:28: undefined: syscall.AF_PACKET
collectors/dnssniffer.go:167:71: undefined: syscall.ETH_P_ALL
collectors/dnssniffer.go:179:9: undefined: syscall.SockaddrLinklayer
collectors/dnssniffer.go:189:54: undefined: syscall.SO_TIMESTAMPNS
collectors/dnssniffer.go:246:26: undefined: syscall.SCM_TIMESTAMPNS
zot12-2:dns-collector jtodd$ go version
go version go1.17.6 darwin/amd64
zot12-2:dns-collector jtodd$

**Comment by dmachard** [comment]
MacOS is not yet supported. In fact, the `dns-colllector` is Linux dependant because of the sniffer.
Any helps will be appreciated to support MacOS.

**Comment by johnhtodd** [comment]
OK good to know.

Also tried on Ubuntu 20.04 and got different errors but on vacation today so no ability to cut/paste the output.

JT

**Comment by dmachard** [comment]
Binaries v0.19.0 released!
